name: VyrimCore
version: '${version}'

main: net.vyrim.core.VyrimCore
api-version: '1.21.11'

softdepend: [LuckPerms, PlaceholderAPI, MythicLib]
loadbefore: [MMOItems]

commands:
  vyrimcore:
    description: Core administrative management command
    permission: vyrimcore.admin.reload
    usage: /<command> reload [module]

permissions:
  vyrimcore.admin.reload:
    description: Allows reloading VyrimCore configuration and modules
    default: op
  vyrimcore.bypass.biomecompass:
    description: Allows bypassing the Biome Compass search cooldown
    default: op
