name: VyrimCore
version: '${version}'

main: net.vyrim.core.VyrimCore
api-version: '1.21.11'

softdepend: [LuckPerms, PlaceholderAPI, MMOItems, MythicLib]

commands:
  vyrimcore:
    description: Core administrative management command
    permission: vyrimcore.command.reload
    usage: /<command> reload [module]
